services:
  agent-validator:
    image: redteamsubnet61/agent-validator:2.0.0-251224
    build:
      context: .
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      HF_TOKEN: "${HF_TOKEN}"
      RT_VALIDATOR_HF_REPO: ${RT_VALIDATOR_HF_REPO}
    env_file:
      - path: .env
        required: false
    volumes:
      - "./volumes/storage/sidecar-btcli/data:/var/lib/sidecar-btcli"
      - "./volumes/storage/agent-validator/logs:/var/log/agent-validator"
      - "./volumes/storage/agent-validator/data:/var/lib/agent-validator"
    tty: true
